defw:
    environment:
        DEFW_PATH: ${HOME}/ORNL/Quantum/QFw/defw
    parent-address: 127.0.0.1
    parent-port: 8090
    parent-name: dirsvc
    name: dirsvc
    shell: interactive
    type: dirsvc
    path: ${DEFW_PATH}
    tmp: ${HOME}/tmp/dirsvc
    loglevel: all
